### ISSUE TITLE
Please support Node v10.x.

### ISSUE THREAD

**Issue by terurou** [HaxeFoundation/hxnodejs#127]
hxnodejs supports Node v6.9 now. But Node v6.x is already EOL...
Node v10 is Active LTS.

https://github.com/nodejs/Release

**Comment by Gama11** [comment]
The funny part is that there's even still an open issue about Node 6 support: https://github.com/HaxeFoundation/hxnodejs/issues/72

Not sure if everything there was addressed.

**Comment by Gama11** [comment]
Do you have an idea how much is missing from the hxnodejs externs for full Node v10 support?

**Comment by terurou** [comment]
Umm..., I don't know.
If you create a development branch of `node10`, it will make to create some pull-requests easy.

**Comment by Gama11** [comment]
I think it's fine to just merge node 10 externs straight to master, that way people can use them right away. :)

**Comment by dionjwa** [comment]
I agree with @Gama11 actually. Normally I would be against an ad-hoc, partial process like just adding nodev10 externs directly, I'd want to do it properly. But the reality is that we don't have the resources (otherwise it would be done), and in any case, working with Haxe+Node I find we often need to use dynamic typing from time to time anyway, since there is no perfect story for managing both haxe and node and npm library versions. So in an imperfect world, I would just like to get people's contributions in quickly, so it can be more useful, even if not perfect.

**Comment by terurou** [comment]
#143
