### ISSUE TITLE
Quickstart guide

### ISSUE THREAD

**Issue by fullofcaffeine** [HaxeFoundation/hxnodejs#38]
For a newcomer, it's right now quite confusing to start with hxnodejs. Considering hxnodejs should the official set of Haxe externs for Nodejs and that it's already being used by other libs/frameworks out there (like Franco's Abe) I'm surprised we don't have more documentation, particularly on how to actually set it up for new Haxe nodejs projects.

Also, a quick mention of other externs and their relationship to this one (and why the user should pick this one over the others already available) would be nice. 

As a side question - does anyone know why https://github.com/clemos/haxe-js-kit isn't the official nodejs extern repo instead? It seems to be under quite active development.

**Comment by eduardo-costa** [comment]
Regarding haxe-js-kit, maybe it implements Node non-canon libraries like Mongoose. It could've started including the nodejs API but I suggest you use the HaxeFoundation backed one because it makes use of the most current Haxe features and is community maintained.

As this is a new "platform" it is in its early stages. So they are probably waiting improvements to officially announce it.

But using it is simple using the `git` flag of `haxelib`
`haxelib git [project-name] [git-clone-path] [branch] [subdirectory]`

Also the documentation area of Haxe can be pulled and improved by everyone :)

**Comment by fullofcaffeine** [comment]
@eduardo-costa Yest, it's simple, but it's not mentioned anywhere in the README. For someone already used to Haxe and its tools, it's easy, for a newcomer, this is a big deal. But yeah, I'll add that line in the README and submit a PR ;)

**Comment by fullofcaffeine** [comment]
@clemos Do you plan on using hxnodejs when it's released for the haxe-js-kit externs?

**Comment by clemos** [comment]
Yes sure, I plan to remove nodejs core externs from haxe-js-kit when hxnodejs is released, and focus on third parties (express, mongoose, react, ...) and tooling (npm, macros, build tools, ...)

**Comment by nadako** [comment]
I've added a really simple quick-start guide in the README (install/example/compile/success), but I don't think this repo is the right place to write comparisons to other libs. Some blog post would be nicer IMO. If that's okay with you, I'd like to close this issue.
